### ISSUE TITLE
node fails with type error

### ISSUE THREAD

**Issue by vrl2** [nvonbulow/hangouts-converter#1]
Hello,

Thanks for creating this tool! I'm new to Node.JS, and there might be an easy workaround for this. It installs fine with npm install, but when I try to run it, I get this error. Running it on Mac OS High Sierra - happy to provide any more details that would help me run it. Thanks!

$ node main > 'output.xml'

/Users/venkat/Desktop/hangouts-converter-master/Hangouts.js:290
  data['conversation_state'].forEach(function(conversation) {
                             ^

TypeError: Cannot read property 'forEach' of undefined
    at new Hangouts (/Users/venkat/Desktop/hangouts-converter-master/Hangouts.js:290:30)
    at Object.<anonymous> (/Users/venkat/Desktop/hangouts-converter-master/main.js:6:29)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
    at Function.Module._load (internal/modules/cjs/loader.js:520:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:719:10)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:575:3)

**Comment by nvonbulow** [comment]
I suspect your `Hangouts.json` file might be empty. Just a reminder that the `Hangouts.json` file goes in the same directory as `main.js`. I would also recommend using the `develop` branch since that rewrite includes support for images (only as a hyperlink at this point).

**Comment by vrl2** [comment]
Thanks for getting back to me. Hangouts.json is 189M. I double checked that it is in the same directory as main.js, and I get the same errors whether I'm using the develop branch or the master branch.

**Comment by nvonbulow** [comment]
Can you download the utility [jq](https://stedolan.github.io/jq/) and post the output of `jq 'keys' -r Hangouts.json`?

**Comment by Birdehub** [comment]
I am getting a similar issue. My Hangouts.json file is 222,300 KB large, if that helps

**Output:**
\hangouts-converter-master\Hangouts.js:290
  data['conversation_state'].forEach(function(conversation) {
                             ^

TypeError: Cannot read property 'forEach' of undefined
    at new Hangouts (\hangouts-converter-master\Hangouts.js:290:30)
    at Object.<anonymous> (\hangouts-converter-master\main.js:6:29)
    at Module._compile (internal/modules/cjs/loader.js:702:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:713:10)
    at Module.load (internal/modules/cjs/loader.js:612:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:551:12)
    at Function.Module._load (internal/modules/cjs/loader.js:543:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:10)
    at startup (internal/bootstrap/node.js:238:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:572:3)

**I downloaded jq. Here is the output**

\hangouts-converter-master>jq-win64 keys -r Hangouts.json
[
  "conversations"
]

**Comment by nvonbulow** [comment]
@Birdehub thanks for the info. It looks like my Hangouts.json file format is different from yours. Google may have changed the file format since I wrote this utility over a year ago. I'll see if I can get an updated version of my data and test with that

**Comment by vrl2** [comment]
Thanks for looking into it! In case it helps, my output from JQ is the same as @Birdehub:
$ jq 'keys' -r Hangouts.json 
[
  "conversations"
]

**Comment by Birdehub** [comment]
@nvonbulow Just curious if you have the free time to explore this? If not, I understand, just wanted to know if I should search for other solutions.  Appreciate the responsiveness and time!

**Comment by nvonbulow** [comment]
@Birdehub I do have limited free time, but I should be able to create a fix by the end of the next weekend, maybe earlier

**Comment by nvonbulow** [comment]
@Birdehub @vrl2 sorry I haven't gotten back to you two yet. I've been very busy getting ready for and with school the past several months. It looks like the file format change is very significant, and I just haven't had the time to rewrite the program at all.
